### ISSUE TITLE
syntax error in ZCL_ZABAP_TABLE_EDIT (usage of zcx_exception)

### ISSUE THREAD

**Issue by WegnerDan** [Kaszub09/ZABAP_TABLE_EDIT#1]
![image](https://github.com/Kaszub09/ZABAP_TABLE_EDIT/assets/6908247/369072d7-fd8d-423e-86ff-9e62a8dff804)

zcx_exception is not included in this repo and is used in two spots in class ZCL_ZABAP_TABLE_EDIT

https://github.com/Kaszub09/ZABAP_TABLE_EDIT/blob/cd8645ef3c2bf974bbc53dde0fd2e519a987b10a/src/zcl_zabap_table_edit.clas.abap#L253

https://github.com/Kaszub09/ZABAP_TABLE_EDIT/blob/cd8645ef3c2bf974bbc53dde0fd2e519a987b10a/src/zcl_zabap_table_edit.clas.abap#L265

**Comment by Kaszub09** [comment]
Hey,
I forgot to update exception name when creating copy for git. Thanks for noticing, fixed 37a711f

**Comment by WegnerDan** [comment]
Thanks
