### ISSUE TITLE
Some gui status texts are in polish (probably)

### ISSUE THREAD

**Issue by WegnerDan** [Kaszub09/ZABAP_TABLE_EDIT#3]
I will fork and try to fix this, but I also want to open this issue to record this.

Some texts in gui status DYNAMIC_COMMANDS are in what looks like polish to me.
https://github.com/Kaszub09/ZABAP_TABLE_EDIT/blob/d2d3566e729c279d162ae249603a94ebb94cf6d1/src/screen/zabap_screen_with_containe.fugr.xml#L483

I am logged in in German.

![image](https://github.com/Kaszub09/ZABAP_TABLE_EDIT/assets/6908247/43d607b9-cf10-4a4a-9b1b-0470bb9d50d5)

The texts at the top of the screen are program texts of class zcl_zabap_table_edit_screen, the buttons at the bottom are from the gui status mentioned above.   
The original language is set as english, so I think these texts should be english also. I can't find the original language of the gui status in the xml, though.

![image](https://github.com/Kaszub09/ZABAP_TABLE_EDIT/assets/6908247/1f5d30c5-431f-4b8c-83ed-17ec39b91fa7)

![image](https://github.com/Kaszub09/ZABAP_TABLE_EDIT/assets/6908247/2f3d4a32-0baa-402f-a6fa-6ec3b4002c0d)

**Comment by WegnerDan** [comment]
I think this should fix it.

https://github.com/WegnerDan/ZABAP_TABLE_EDIT/commit/7d947a221f6234a58d6e319b421cbf7302b003f7

~~I'm gonna add a german translation and then create a PR~~

I can't get abapgit to pick up the translation, so this PR should suffice:

https://github.com/Kaszub09/ZABAP_TABLE_EDIT/pull/4

**Comment by Kaszub09** [comment]
Yeah, I'm logged mostly in polish language and that was probably the case when I was creating menu, hence wrong language. Thanks, I've merged it.
As for another translations, my guess would be (unless you have already tried :)) this option
![obraz](https://github.com/Kaszub09/ZABAP_TABLE_EDIT/assets/34368953/014a3701-6278-4a31-b1fa-311d707c9e0c)
![obraz](https://github.com/Kaszub09/ZABAP_TABLE_EDIT/assets/34368953/407d6686-81ad-436a-946e-4d67a09853ad)
But I think it may simply not support translation of all objects?
Or trying something like that https://docs.abapgit.org/user-guide/reference/translations.html#new-approach. 
But I'm not sure it's all worth the hassle.
